webtalk_init -webtalk_dir /home/controls/Pallavi/Bare_AMP_Zed/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 21 12:36:08 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174141122_174141123_210588270_824" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aevbhlvrm2tkhq4djhq6hjs6l6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1437434915000" -context "sdk\\\\application/1437434915000"
webtalk_add_data -client sdk -key hwid -value "1435635061000" -context "sdk\\\\application/1437434915000"
webtalk_add_data -client sdk -key bspid -value "1435636221000" -context "sdk\\\\application/1437434915000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1437434915000"
webtalk_add_data -client sdk -key os -value "freertos_zynq" -context "sdk\\\\application/1437434915000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1437434915000"
webtalk_transmit -clientid 840342066 -regid "174141122_174141123_210588270_824" -xml /home/controls/Pallavi/Bare_AMP_Zed/webtalk/usage_statistics_ext_sdk.xml -html /home/controls/Pallavi/Bare_AMP_Zed/webtalk/usage_statistics_ext_sdk.html -wdm /home/controls/Pallavi/Bare_AMP_Zed/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
